//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeToolSharp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeIgnoreBackground {
            get {
                return ((bool)(this["ThemeIgnoreBackground"]));
            }
            set {
                this["ThemeIgnoreBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeIgnoreCursor {
            get {
                return ((bool)(this["ThemeIgnoreCursor"]));
            }
            set {
                this["ThemeIgnoreCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeIgnoreDesktopIcons {
            get {
                return ((bool)(this["ThemeIgnoreDesktopIcons"]));
            }
            set {
                this["ThemeIgnoreDesktopIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeIgnoreColor {
            get {
                return ((bool)(this["ThemeIgnoreColor"]));
            }
            set {
                this["ThemeIgnoreColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeIgnoreSound {
            get {
                return ((bool)(this["ThemeIgnoreSound"]));
            }
            set {
                this["ThemeIgnoreSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeIgnoreScreensaver {
            get {
                return ((bool)(this["ThemeIgnoreScreensaver"]));
            }
            set {
                this["ThemeIgnoreScreensaver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeUnknownFlag1 {
            get {
                return ((bool)(this["ThemeUnknownFlag1"]));
            }
            set {
                this["ThemeUnknownFlag1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeUnknownFlag2 {
            get {
                return ((bool)(this["ThemeUnknownFlag2"]));
            }
            set {
                this["ThemeUnknownFlag2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThemeDoNotSetLogonUi {
            get {
                return ((bool)(this["ThemeDoNotSetLogonUi"]));
            }
            set {
                this["ThemeDoNotSetLogonUi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InitUnknownFlag1 {
            get {
                return ((bool)(this["InitUnknownFlag1"]));
            }
            set {
                this["InitUnknownFlag1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InitUnknownFlag2 {
            get {
                return ((bool)(this["InitUnknownFlag2"]));
            }
            set {
                this["InitUnknownFlag2"] = value;
            }
        }
    }
}
